AlfredoRamos/phpbb-ext-seo-metadata

includes/helper.php

Use DOM to extract images instead of regular expressions

---

adm/style/acp_seo_metadata_settings.html
controller/acp.php
includes/helper.php
language/en/acp/info_acp_settings.php
language/es/acp/info_acp_settings.php
language/es_x_tu/acp/info_acp_settings.php
migrations/v10x/m1_seometadata_data.php
tests/functional/seometadata_test.php

Add support for attachment images

---

adm/style/acp_seo_metadata_settings.html
controller/acp.php
event/listener.php
includes/helper.php
language/en/acp/info_acp_settings.php
language/es/acp/info_acp_settings.php
language/es_x_tu/acp/info_acp_settings.php
migrations/v10x/m1_seometadata_data.php
tests/functional/seometadata_test.php

This commit reduces the calls for `clean_description()`, `clean_image()` and `clean_url()`
Fixes #7

Add support for description metatag and minor improvements

---

migrations/v10x/m00_configuration.php
migrations/v11x/m00_configuration.php

Fix migration files

---

README.md
adm/style/acp_seo_metadata_settings.html
config/services.yml
controller/acp.php
event/listener.php
includes/helper.php
language/en/acp/info_acp_settings.php
migrations/v12x/m00_configuration.php

Add Open Graph image width, height and MIME type

---

config/services.yml
includes/helper.php
tests/functional/seometadata_test.php

Fix Open Graph localization name

---

language/es/acp/info_acp_settings.php
language/es_x_tu/acp/info_acp_settings.php

Update Spanish translations

---

includes/helper.php

It fixes some localization names where the country code (ISO 3166-2) is the same as the language code (ISO 639-1), like `es_ES`, `de_DE`, etc.
It's another approach of #15 
Fixes #10

Fix Open Graph tags

---

includes/helper.php
tests/functional/seometadata_test.php

Fix image URL regression in clean_image() method

---

event/listener.php
includes/helper.php
styles/all/template/seo_metadata.html

Code refactoring

---

README.md
adm/style/acp_seo_metadata_settings.html
controller/acp.php
event/listener.php
includes/helper.php
language/en/acp/info_acp_settings.php
language/es/acp/info_acp_settings.php
language/es_x_tu/acp/info_acp_settings.php
migrations/v13x/m00_configuration.php
tests/functional/seometadata_test.php
travis/setup-extension-dependencies.sh

Add missing JSON-LD data

---

includes/helper.php

Recursive removal of empty metadata values

---

event/listener.php
tests/event/listener_test.php
tests/functional/seometadata_test.php

Fix forum description

---

config/services.yml
controller/acp.php
event/listener.php
includes/helper.php

Helper improvements

---

includes/helper.php

Bug introduced in commit https://github.com/AlfredoRamos/phpbb-ext-seo-metadata/commit/2b74c79359a96769d37ea8cbf1196bb881723c4d
Fixes #39

Fix bug in helper::extract_image() method

---

controller/acp.php
includes/helper.php
language/en/acp/settings.php
language/es/acp/settings.php
language/es_x_tu/acp/settings.php

Add image validation

---

adm/style/acp_seo_metadata_settings.html
config/services.yml
controller/acp.php
event/listener.php
includes/helper.php
language/en/acp/settings.php
language/es/acp/settings.php
language/es_x_tu/acp/settings.php
migrations/v13x/m00_configuration.php
tests/event/listener_test.php
tests/functional/seometadata_test.php

Add post-based metadata

---

.travis.yml
README.md
composer.json
config/services.yml
ext.php
includes/helper.php
tests/event/listener_test.php
tests/functional/seometadata_test.php
travis/prepare-epv.sh
travis/prepare-phpbb.sh

Prepare for phpBB 3.3.x

---

includes/helper.php

Fix image extraction warning

---

adm/style/acp_seo_metadata_settings.html
tests/functional/acp_seometadata_test.php

Improve image metadata display in ACP

---

includes/helper.php

Fix image info issue in helper::image_validate()

---

includes/helper.php

Remove any SID in the URL, not just the one generated by the current user.

Improve URL cleaning

---

includes/helper.php
tests/functional/seometadata_test.php

Add JSON-LD articleSection

---

.travis.yml
composer.json

Add PHP 8 tests

---

.github/setup-extension.sh
.github/setup-tests.sh
.github/workflows/ci.yml
README.md

Build the extension package for production environments using Phing, and use those files to prevent issues with EPV and sniffers when development files are included.

Improve tests

---

includes/helper.php
tests/functional/seometadata_test.php

This would allow to extract images URLs with parameters.
Fixes #81

Handle image URLs with parameters.

---

event/listener.php
includes/helper.php
tests/functional/seometadata_test.php

Fix description prefix for all cases, and avoid code repetition.
Also, after some testing, DOM manipulation might not be needed at all.

Improve prefixed description

---

tests/functional/seometadata_test.php

Add missing functional tests

---

.github/workflows/ci.yml
README.md
build.xml
config/services.yml
event/listener.php
includes/helper.php
tests/functional/seometadata_test.php

Improve author meta data

---

language/cs/acp/settings.php
language/fr/acp/settings.php
language/ru/acp/info_acp_common.php
language/ru/acp/settings.php

Translations updates from Crowdin
